services:

  postgres:
    image: postgres:18.0-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: praktikum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
