version: '3'

env:
  BIN: "{{.PWD}}/bin"

tasks:
  build:
    desc: Build all
    cmds:
      - "go build -o $BIN/server ./cmd/server"
      - "go build -o $BIN/agent ./cmd/agent"

  server:
    desc: Run server, specify args after --
    cmds:
      - "go build -o $BIN/server ./cmd/server"
      - "$BIN/server {{.CLI_ARGS}}"

  agent:
    desc: Run agent, specify args after --
    cmds:
      - "go build -o $BIN/agent ./cmd/agent"
      - "$BIN/agent {{.CLI_ARGS}}"

  test-build:
    desc: Rebuild docker image for yandex tests
    cmds:
      - docker-compose build --no-cache

  test-all:
    desc: Run all linters and tests
    cmds:
      # - task lint
      - task test
      - docker compose down --remove-orphans
      - docker compose up

  test:
    desc: Run local unit tests
    cmds:
      - "go test -race ./..."

  fmt:
    desc: Format and fix imports
    cmds:
      - "gofmt -w ."
      - "goimports -w -local \"github.com/mikeziminio/go-custom-metrics\" ."

  lint-prepare:
    desc: Install golangci-lint and nilaway, verify golangci-lint config
    cmds:
      - "GOBIN=$BIN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0"
      - "GOBIN=$BIN go install go.uber.org/nilaway/cmd/nilaway@latest"
      - "$BIN/golangci-lint cache clean"
      - "$BIN/golangci-lint config verify"

  lint:
    desc: Run yandex and local linters
    cmds:
      - "$BIN/golangci-lint run -c .golangci.yml"
      - "$BIN/nilaway ./cmd/server"
      - "$BIN/nilaway ./cmd/agent"

  mockery:
    desc: Run mockery - update mock files
    cmds:
      - mockery

  default:
    cmds:
      - "task -l"
      - "echo Bin directory: $BIN"
    silent: true
