// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"context"

	"github.com/mikeziminio/go-custom-metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage) Get(ctx context.Context, metricType model.MetricType, metricName string) (*model.Metric, error) {
	ret := _mock.Called(ctx, metricType, metricName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Metric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.MetricType, string) (*model.Metric, error)); ok {
		return returnFunc(ctx, metricType, metricName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.MetricType, string) *model.Metric); ok {
		r0 = returnFunc(ctx, metricType, metricName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Metric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.MetricType, string) error); ok {
		r1 = returnFunc(ctx, metricType, metricName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - metricType model.MetricType
//   - metricName string
func (_e *MockStorage_Expecter) Get(ctx interface{}, metricType interface{}, metricName interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, metricType, metricName)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, metricType model.MetricType, metricName string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.MetricType
		if args[1] != nil {
			arg1 = args[1].(model.MetricType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(metric *model.Metric, err error) *MockStorage_Get_Call {
	_c.Call.Return(metric, err)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(ctx context.Context, metricType model.MetricType, metricName string) (*model.Metric, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStorage
func (_mock *MockStorage) List(ctx context.Context) (map[string]model.Metric, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 map[string]model.Metric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]model.Metric, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]model.Metric); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]model.Metric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) List(ctx interface{}) *MockStorage_List_Call {
	return &MockStorage_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockStorage_List_Call) Run(run func(ctx context.Context)) *MockStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_List_Call) Return(stringToMetric map[string]model.Metric, err error) *MockStorage_List_Call {
	_c.Call.Return(stringToMetric, err)
	return _c
}

func (_c *MockStorage_List_Call) RunAndReturn(run func(ctx context.Context) (map[string]model.Metric, error)) *MockStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockStorage
func (_mock *MockStorage) Restore(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockStorage_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Restore(ctx interface{}) *MockStorage_Restore_Call {
	return &MockStorage_Restore_Call{Call: _e.mock.On("Restore", ctx)}
}

func (_c *MockStorage_Restore_Call) Run(run func(ctx context.Context)) *MockStorage_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Restore_Call) Return(err error) *MockStorage_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Restore_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorage_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockStorage
func (_mock *MockStorage) Sync(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockStorage_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Sync(ctx interface{}) *MockStorage_Sync_Call {
	return &MockStorage_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *MockStorage_Sync_Call) Run(run func(ctx context.Context)) *MockStorage_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Sync_Call) Return(err error) *MockStorage_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Sync_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorage_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorage
func (_mock *MockStorage) Update(ctx context.Context, m model.Metric) (*model.Metric, error) {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Metric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Metric) (*model.Metric, error)); ok {
		return returnFunc(ctx, m)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Metric) *model.Metric); ok {
		r0 = returnFunc(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Metric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Metric) error); ok {
		r1 = returnFunc(ctx, m)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - m model.Metric
func (_e *MockStorage_Expecter) Update(ctx interface{}, m interface{}) *MockStorage_Update_Call {
	return &MockStorage_Update_Call{Call: _e.mock.On("Update", ctx, m)}
}

func (_c *MockStorage_Update_Call) Run(run func(ctx context.Context, m model.Metric)) *MockStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Metric
		if args[1] != nil {
			arg1 = args[1].(model.Metric)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Update_Call) Return(metric *model.Metric, err error) *MockStorage_Update_Call {
	_c.Call.Return(metric, err)
	return _c
}

func (_c *MockStorage_Update_Call) RunAndReturn(run func(ctx context.Context, m model.Metric) (*model.Metric, error)) *MockStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Updates provides a mock function for the type MockStorage
func (_mock *MockStorage) Updates(ctx context.Context, metrics []model.Metric) error {
	ret := _mock.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Metric) error); ok {
		r0 = returnFunc(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Updates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updates'
type MockStorage_Updates_Call struct {
	*mock.Call
}

// Updates is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []model.Metric
func (_e *MockStorage_Expecter) Updates(ctx interface{}, metrics interface{}) *MockStorage_Updates_Call {
	return &MockStorage_Updates_Call{Call: _e.mock.On("Updates", ctx, metrics)}
}

func (_c *MockStorage_Updates_Call) Run(run func(ctx context.Context, metrics []model.Metric)) *MockStorage_Updates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Metric
		if args[1] != nil {
			arg1 = args[1].([]model.Metric)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Updates_Call) Return(err error) *MockStorage_Updates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Updates_Call) RunAndReturn(run func(ctx context.Context, metrics []model.Metric) error) *MockStorage_Updates_Call {
	_c.Call.Return(run)
	return _c
}
