// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbstorage

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockClassifier creates a new instance of mockClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClassifier {
	mock := &mockClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockClassifier is an autogenerated mock type for the classifier type
type mockClassifier struct {
	mock.Mock
}

type mockClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClassifier) EXPECT() *mockClassifier_Expecter {
	return &mockClassifier_Expecter{mock: &_m.Mock}
}

// ClassifyError provides a mock function for the type mockClassifier
func (_mock *mockClassifier) ClassifyError(err error) ErrorClass {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for ClassifyError")
	}

	var r0 ErrorClass
	if returnFunc, ok := ret.Get(0).(func(error) ErrorClass); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(ErrorClass)
	}
	return r0
}

// mockClassifier_ClassifyError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifyError'
type mockClassifier_ClassifyError_Call struct {
	*mock.Call
}

// ClassifyError is a helper method to define mock.On call
//   - err error
func (_e *mockClassifier_Expecter) ClassifyError(err interface{}) *mockClassifier_ClassifyError_Call {
	return &mockClassifier_ClassifyError_Call{Call: _e.mock.On("ClassifyError", err)}
}

func (_c *mockClassifier_ClassifyError_Call) Run(run func(err error)) *mockClassifier_ClassifyError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockClassifier_ClassifyError_Call) Return(errorClass ErrorClass) *mockClassifier_ClassifyError_Call {
	_c.Call.Return(errorClass)
	return _c
}

func (_c *mockClassifier_ClassifyError_Call) RunAndReturn(run func(err error) ErrorClass) *mockClassifier_ClassifyError_Call {
	_c.Call.Return(run)
	return _c
}
