// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbstorage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRetrier creates a new instance of MockRetrier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetrier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetrier {
	mock := &MockRetrier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRetrier is an autogenerated mock type for the Retrier type
type MockRetrier struct {
	mock.Mock
}

type MockRetrier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetrier) EXPECT() *MockRetrier_Expecter {
	return &MockRetrier_Expecter{mock: &_m.Mock}
}

// Retry provides a mock function for the type MockRetrier
func (_mock *MockRetrier) Retry(f func() error) error {
	ret := _mock.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for Retry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func() error) error); ok {
		r0 = returnFunc(f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRetrier_Retry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retry'
type MockRetrier_Retry_Call struct {
	*mock.Call
}

// Retry is a helper method to define mock.On call
//   - f func() error
func (_e *MockRetrier_Expecter) Retry(f interface{}) *MockRetrier_Retry_Call {
	return &MockRetrier_Retry_Call{Call: _e.mock.On("Retry", f)}
}

func (_c *MockRetrier_Retry_Call) Run(run func(f func() error)) *MockRetrier_Retry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() error
		if args[0] != nil {
			arg0 = args[0].(func() error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRetrier_Retry_Call) Return(err error) *MockRetrier_Retry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRetrier_Retry_Call) RunAndReturn(run func(f func() error) error) *MockRetrier_Retry_Call {
	_c.Call.Return(run)
	return _c
}
