// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package retrier

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRetryClassifier creates a new instance of MockRetryClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetryClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetryClassifier {
	mock := &MockRetryClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRetryClassifier is an autogenerated mock type for the RetryClassifier type
type MockRetryClassifier struct {
	mock.Mock
}

type MockRetryClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetryClassifier) EXPECT() *MockRetryClassifier_Expecter {
	return &MockRetryClassifier_Expecter{mock: &_m.Mock}
}

// ClassifyError provides a mock function for the type MockRetryClassifier
func (_mock *MockRetryClassifier) ClassifyError(err error) ErrorClass {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for ClassifyError")
	}

	var r0 ErrorClass
	if returnFunc, ok := ret.Get(0).(func(error) ErrorClass); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(ErrorClass)
	}
	return r0
}

// MockRetryClassifier_ClassifyError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifyError'
type MockRetryClassifier_ClassifyError_Call struct {
	*mock.Call
}

// ClassifyError is a helper method to define mock.On call
//   - err error
func (_e *MockRetryClassifier_Expecter) ClassifyError(err interface{}) *MockRetryClassifier_ClassifyError_Call {
	return &MockRetryClassifier_ClassifyError_Call{Call: _e.mock.On("ClassifyError", err)}
}

func (_c *MockRetryClassifier_ClassifyError_Call) Run(run func(err error)) *MockRetryClassifier_ClassifyError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRetryClassifier_ClassifyError_Call) Return(errorClass ErrorClass) *MockRetryClassifier_ClassifyError_Call {
	_c.Call.Return(errorClass)
	return _c
}

func (_c *MockRetryClassifier_ClassifyError_Call) RunAndReturn(run func(err error) ErrorClass) *MockRetryClassifier_ClassifyError_Call {
	_c.Call.Return(run)
	return _c
}
